# Test:
# cd seed/config/ansible
# ansible-playbook -i ./inventory/inventory-default.yml ./site.yml --tags seed,setup
---
- name: Setup seed device(s)
  hosts: seed
  become: yes

  roles:
    - role: setup-seed
      tags:
        - setup
        - seed
