# SPDX-License-Identifier: MIT-0
---
# defaults file for setup-seed

packages_list_setup_seed:
 - ansible
 - build-essential
 - git
 - golang-go
 - iputils-ping
 - minicom
 - nano
 - net-tools
 - screen
 - telnet
 - tftp-hpa:armhf
 - tftpd-hpa
 - vlan
 - wget

apt_cache_valid_time: 3600

# Kernel modules to load
kernel_modules:
  - 8021q
