# SPDX-License-Identifier: MIT-0
---
# defaults file for setup-seed

packages_list_setup_seed:
 - ansible
 - build-essential
 - git
 - golang-go
 - iputils-ping
 - minicom
 - nano
 - net-tools
 - p7zip-full
 - screen
 - telnet
 - tftp-hpa:armhf
 - tftpd-hpa
 - ufw
 - vlan
 - wget

apt_cache_valid_time: 3600

# Kernel modules to load
kernel_modules:
 - 8021q

# VLAN configuration
primary_interface: eth0
vlan6_address: "172.16.0.20"
vlan7_address: "10.0.0.20"
vlan8_address: "192.168.0.20"

# TFTP configuration
tftp_username: tftp
tftp_directory: /opt/tftpboot
tftp_address: "{{ vlan6_address | ansible_host | default('172.16.0.20') }}:69"
tftp_options: "--secure"

tftp_subdirectories:
 - AP-C9100
 - SW-IE4000

tftp_directory_mode: "0777"
skip_reboot: false
