# SPDX-License-Identifier: MIT-0
---
# defaults file for setup-seed

setup_seed_packages_list:
 - ansible
 - build-essential
 - git
 - git-lfs
 - golang-go
 - iputils-ping
 - minicom
 - nano
 - net-tools
 - p7zip-full
 - p7zip-rar
 - screen
 - telnet
 - tftp-hpa:armhf
 - tftpd-hpa
 - ufw
 - vlan
 - wget

setup_seed_apt_cache_valid_time: 3600

# Kernel modules to load
setup_seed_kernel_modules:
 - 8021q

# VLAN configuration
setup_seed_primary_interface: eth0
setup_seed_vlan6_address: "172.16.0.20"
setup_seed_vlan7_address: "10.0.0.20"
setup_seed_vlan8_address: "192.168.0.20"

# TFTP configuration
setup_seed_tftp_username: tftp
setup_seed_tftp_directory: /opt/tftpboot
setup_seed_tftp_address: "{{ vlan6_address | default('172.16.0.20') }}:69"
setup_seed_tftp_options: "--secure"

setup_seed_tftp_directory_mode: "0777"
setup_seed_skip_reboot: false

setup_seed_firmware_prompt_user: true
setup_seed_firmware_auto_extract: false
setup_seed_firmware_archive_name: tftp-network-firmware.7z
setup_seed_firmware_archive_path: "{{ role_path }}/files/{{ setup_seed_firmware_archive_name }}"

setup_seed_firmware_directories:
 - AP-C9100
 - SW-IE4000
