all:
 children:
  network:
   hosts:
    r0:
     ansible_host: 172.16.0.1
    sw0:
     ansible_host: 172.16.0.2
    ap0:
     ansible_host: 172.16.0.3
   children:
    network:switch:
     hosts:
      sw0:
       ansible_host: 172.16.0.2
    network:router:
     hosts:
      r0:
       ansible_host: 172.16.0.1
    network:ap:
     hosts:
      ap0:
       ansible_host: 172.16.0.3
  seed:
   hosts:
    seed0:
     ansible_host: 172.16.0.20
  garden:
   hosts:
    garden0:
     ansible_host: 172.16.0.20
 vars:
  ansible_ssh_pass: password
  ansible_user: admin
  ansible_port: 22
  ansible_connection: ssh
