# Test:
# cd repo root dir
# ansible seed -i ./seed/config/ansible/inventory/inventory-default.yml -m ping
# or
# ansible all -i ./seed/config/ansible/inventory/inventory-default.yml -m ping

all:
 children:
  network:
   hosts:
    r0:
     ansible_host: 172.16.0.1
    sw0:
     ansible_host: 172.16.0.2
    ap0:
     ansible_host: 172.16.0.3
   children:
    network_switch:
     hosts:
      sw0:
       ansible_host: 172.16.0.2
    network_router:
     hosts:
      r0:
       ansible_host: 172.16.0.1
    network_ap:
     hosts:
      ap0:
       ansible_host: 172.16.0.3
  seed:
   hosts:
    seed0:
     ansible_host: 172.16.0.20
  garden:
   hosts:
    garden0:
     ansible_host: 172.16.0.21
 vars:
  ansible_user: growbox
  ansible_ssh_pass: grow
  ansible_port: 22
  ansible_connection: ssh
  ansible_ssh_common_args: '-o BindAddress=172.16.0.20 -o StrictHostKeyChecking=no'
  host_key_checking: False
  ansible_python_interpreter: auto_silent
